apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: im5s0igk3-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-dotnet-basic:f2444f1b3987b0e3a55d1d3e000c041cb9f8a926@sha256:2c9b3d8c24d7864cdbc85e1558cb0d0cdb18aa400211451abd85f00e5718758f
          name: container-image
